---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: nginx-1-repository
  namespace: bas-ns
spec:
  # The interval at wich to check the upstream for updates
  interval: 2m
  # The repository URL, a valid URL contains at least a protocol and host
  url: https://github.com/bhargavimandala/helm-charts/helm-nginx-chart

---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx-1-release
  namespace: bas-ns
spec:
  # The interval at which to reconcile the Helm release
  interval: 2m
  chart:
    spec:
      # The name of the chart as made available by the HelmRepository
      # (without any aliases)
      chart: helm-nginx-chart
      # A fixed SemVer, or any SemVer range
      # (i.e. >=4.0.0 <5.0.0)
      version: 0.1.0
      # The reference to the HelmRepository
      sourceRef:
        kind: HelmRepository
        name: nginx-1-repository
        # Optional, defaults to the namespace of the HelmRelease
        namespace: bas-ns
